- CHANGELOG.md
- README.md
Fixes https://github.com/giantswarm/giantswarm/issues/26424
> Updated readme with instructions on adding tests

- CHANGELOG.md
- go.mod
- go.sum
> bump ginkgo v2.9.2 -> v2.9.4

- CHANGELOG.md
- providers/capvcd/standard/test_data/cluster_values.yaml
> Update cluster values for cluster-cloud-director

- CHANGELOG.md
- common/basic.go
- common/common.go
- common/dns.go
- go.mod
- go.sum
- providers/capa/standard/test_data/cluster_values.yaml
- providers/capv/Xstandard/test_data/cluster_values.yaml
- providers/capvcd/standard/test_data/cluster_values.yaml
- providers/capz/standard/test_data/cluster_values.yaml
Tests the common DNS records created for WCs
> Add DNS tests

- CHANGELOG.md
- entrypoint.sh
Generates test result files that can be used to display the overall results when running suites in parallel. 
Towards: https://github.com/giantswarm/giantswarm/issues/26717
Linked with: https://github.com/giantswarm/tekton-resources/pull/121
> Generate test result reports for each test suite

- CHANGELOG.md
- README.md
Updated the readme with up-to-date info and added section about running in CI.
> Updated readme with more up-to-date info

- CHANGELOG.md
- providers/capa/standard/test_data/cluster_values.yaml
- providers/capa/upgrade/test_data/cluster_values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/27925
> Use spot instances for CAPA tests

- README.md
> Update docs on running locally

- CHANGELOG.md
- providers/capv/standard/test_data/cluster_values.yaml
> Remove hard-coded IP for Service load balancer and use ip pool instead

- CHANGELOG.md
- providers/capv/standard/test_data/cluster_values.yaml
- providers/capv/upgrade/test_data/cluster_values.yaml
> Fix CAPV tests by switching to Flatcar image

- CHANGELOG.md
- internal/common/scale.go
- providers/capv/standard/capv_test.go
- providers/capv/upgrade/capv_test.go
- providers/capvcd/standard/capvcd_test.go
- providers/capvcd/upgrade/capvcd_test.go
- providers/capz/standard/capz_test.go
- providers/capz/upgrade/capz_test.go
Some small cleanup tasks:
* added some relevant comments
* explicitly set false bools
* added logging to scale test
* fixed some copy and paste mistakes
> Various small cleanup tasks

- CHANGELOG.md
- providers/eks/standard/test_data/cluster_values.yaml
- providers/eks/upgrade/test_data/cluster_values.yaml
update values to match new scheme https://github.com/giantswarm/cluster-eks/pull/50
> eks-update-global-values

- providers/capa/standard/capa_test.go
- providers/capa/upgrade/capa_test.go
towards https://github.com/giantswarm/giantswarm/issues/29254
disable bastion test for CAPA as we want to remove it in this PR https://github.com/giantswarm/cluster-aws/pull/455
> capa-disable-bastions

- CHANGELOG.md
- providers/capa/private/capa_suite_test.go
- providers/capa/private/capa_test.go
- providers/capa/private/test_data/cluster_values.yaml
- providers/capa/private/test_data/default-apps_values.yaml
- providers/capa/private/test_data/helloworld_values.yaml
- providers/capa/private/test_data/scale_helloworld_values.yaml
> Add CAPA private WC tests

- CHANGELOG.md
- assets/storage/storage.go
> Make pvc pod run on both PSS and PSP

- .circleci/config.yml
- CHANGELOG.md
- internal/common/basic.go
towards https://github.com/giantswarm/giantswarm/issues/29550
Add 3 tests:
- check all DeploymentSet replicas are ready
- check all StatefulsSets replicas are ready
- check all desired daemon pods are running
> Add tests on DeploymentSets, StatefulSets and DaemonSets to ensure all desired replicas/pods are running

- CHANGELOG.md
- providers/capa/private/capa_test.go
- providers/capa/private/test_data/cluster_values.yaml
- providers/capa/standard/test_data/cluster_values.yaml
- providers/capa/upgrade/test_data/cluster_values.yaml
> Enable cluster autoscaler test in private clusters

- CHANGELOG.md
- providers/capvcd/standard/test_data/cluster_values.yaml
- providers/capvcd/upgrade/test_data/cluster_values.yaml
> capvcd 1.25.13

- CHANGELOG.md
- go.mod
- go.sum
- internal/common/metrics.go
- internal/common/scale.go
> Make error messages actionable for Prometheus metrics query test failures

- CHANGELOG.md
- internal/common/apps.go
> Add security-bundle test

- CHANGELOG.md
- README.md
Fixes: https://github.com/giantswarm/roadmap/issues/3477
> Support testing PRs from Releases repo

- CHANGELOG.md
- go.mod
- go.sum
- internal/common/dns.go
- internal/common/hello.go
Fixes https://github.com/giantswarm/giantswarm/issues/31135
> Switched to using dns and http clients from clustertest

- .circleci/config.yml
> Limit container registries we push to

- README.md
Adds details about the `TARGET_SUITES` and `RELEASE_VERSION` params supported by comment triggers.
Skipping as only readme change
> Update readme with details about comment params

- CHANGELOG.md
- go.mod
- go.sum
> Update clustertest to v1.21.1

- CHANGELOG.md
- go.mod
- go.sum
> Correctly get latest GitHub release for Apps

- CHANGELOG.md
- go.mod
- go.sum
> update standup to add name for capvcd tests

- CHANGELOG.md
- go.mod
- go.sum
> Fix release name for provider which include a hyphen

- go.mod
- go.sum
Reverts giantswarm/cluster-test-suites#680
> Revert "Update github.com/gravitational/teleport/api digest to 1e95c7b"

- CHANGELOG.md
- internal/common/metrics.go
Signed-off-by: Matias Charriere <matias@giantswarm.io>
> Include Cilium in metrics test

- README.md
- internal/common/apps.go
> Fix broken links

- internal/common/apps.go
Reverts the mistaken change included in https://github.com/giantswarm/cluster-test-suites/pull/756/
> Revert mistake commit

- CHANGELOG.md
- internal/common/basic.go
- providers/capa/karpenter/capa_suite_test.go
- providers/capa/karpenter/capa_test.go
- providers/capa/karpenter/test_data/cluster_values.yaml
- providers/capa/karpenter/test_data/helloworld_values.yaml
- providers/capa/karpenter/test_data/scale_helloworld_values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/33615
> Add CAPA karpenter tests
