giantswarm/cluster-test-suites

providers/capvcd/standard/capvcd_test.go
Currently creating WCs will fail once resources are full on the provider, which needs a manaul cleanup to get it working.
=> Pend CAPVCD suite

CHANGELOG.md, providers/capvcd/standard/test_data/cluster_values.yaml
Applies schema changes that are introduced with `0.12.0`.
https://github.com/giantswarm/cluster-cloud-director/releases/tag/v0.12.0
=> Schema changes

CHANGELOG.md, cmd/standup/main.go, go.mod, providers/capa/cluster.go, providers/capa/standard/capa_suite_test.go, providers/capv/cluster.go, providers/capv/standard/capv_suite_test.go, providers/capvcd/cluster.go, providers/capvcd/standard/capvcd_suite_test.go, providers/capz/cluster.go, providers/capz/standard/capz_suite_test.go
- Pulls out the creation of the `Cluster` app to a provider-specific `NewClusterApp` function that abstracts away any cluster-specific logic.
- Fixed the CAPV and CAPVCD clusters to specify the credentials secrets as extra configs that can be referenced cross-namespace. This allows us to use test Orgs with these providers too like CAPA and CAPZ.
=> Abstract provider-specific Cluster App creation

CHANGELOG.md, go.mod, go.sum
Fixes: https://github.com/giantswarm/giantswarm/issues/27743
Updated clustertest to latest version with fix for `GITHUB_TOKEN` issue.
=> Bump clustertest to v0.1.1

CHANGELOG.md, README.md, internal/upgrade/upgrade.go, providers/capa/upgrade/capa_suite_test.go, providers/capa/upgrade/capa_test.go, providers/capa/upgrade/test_data/cluster_values.yaml, providers/capa/upgrade/test_data/default-apps_values.yaml, providers/capv/upgrade/capv_suite_test.go, providers/capv/upgrade/capv_test.go, providers/capv/upgrade/test_data/cluster_values.yaml, providers/capv/upgrade/test_data/default-apps_values.yaml, providers/capvcd/upgrade/capvcd_suite_test.go, providers/capvcd/upgrade/capvcd_test.go, providers/capvcd/upgrade/test_data/cluster_values.yaml, providers/capvcd/upgrade/test_data/default-apps_values.yaml, providers/capz/upgrade/capz_suite_test.go, providers/capz/upgrade/capz_test.go, providers/capz/upgrade/test_data/cluster_values.yaml, providers/capz/upgrade/test_data/default-apps_values.yaml
Adds upgrade test suites that will run from cluster/default-apps App PRs. These tests require the `E2E_OVERRIDE_VERSIONS` to be set so will be skipped when running against `cluster-test-suites`.
The upgrade test suite creates a workload cluster using the latest released versions then waits for the nodes to be in a ready state. It then performs the upgrade by modifying the `version` property of the App on the MC and waits for both the cluster App and the default-apps App to have the expected version deployed. Finally they check for the nodes being in a ready state again (in case the upgrade needs to roll nodes) and then runs the common test specs.
Fixes: https://github.com/giantswarm/roadmap/issues/2679
=> Added Upgrade test suites

CODEOWNERS
Since clippy no longer exists, the file was invalid.
Is it correct to assign CAPZ to phoenix?
=> Update CODEOWNERS in cluster-test-suites

CHANGELOG.md, providers/capv/upgrade/capv_test.go
We don't support bastion for CAPV and upgrade tests are failing because of this check now.
=> Disable bastion tests for CAPV during upgrades

CHANGELOG.md, cmd/standup/main.go, common/dns.go, go.mod, go.sum, internal/upgrade/upgrade.go, providers/capa/standard/capa_suite_test.go, providers/capa/standard/capa_test.go, providers/capa/upgrade/capa_suite_test.go, providers/capv/standard/capv_suite_test.go, providers/capv/upgrade/capv_suite_test.go, providers/capvcd/standard/capvcd_test.go, providers/capvcd/upgrade/capvcd_suite_test.go, providers/capz/standard/capz_test.go, providers/capz/upgrade/capz_suite_test.go
Bump clustertest to v0.3.0 to be able to set app organization.
=> Bump clustertest to v0.3.0

CHANGELOG.md, common/apps.go
- Refactors the app test so that it can log out the progress as it waits for the eventual desired state.
I removed the custom report formatter as the log output should give the same level of information but without waiting for it to fail. I also haven't seen these formatters used for any other tests so seemed a bit odd just having them in place for this one. If you feel its still worth having it included let me know and I'll be happy to add it back.
=> Refactor app tests so they log out progress

.dockerignore, CHANGELOG.md, Dockerfile
This PR attempts to shrink the container image from currently ~3GB down to ~1GB by putting test binaries into a clean debian:slim container image
=> Shrink container image

CHANGELOG.md, common/basic.go, go.mod, go.sum, providers/capa/standard/capa_test.go, providers/capvcd/standard/capvcd_test.go, providers/capz/standard/capz_test.go
- Bumped `clustertest` to v0.3.1 with fix for `ClusterValues` unmarshalling if different `NodePool` types
- Refactored node tests to reuse code now the `NodePool` type fix is in `clustertest`
=> Refactor node tests with new ClusterValues unmarshalling fix

CHANGELOG.md, providers/capa/standard/test_data/cluster_values.yaml, providers/capa/upgrade/test_data/cluster_values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/27925
Rely more on `cluster-aws` defaults. This would allow us to always use the right instance type, which we should have reserved on AWS to save money.
=> Use cluster-aws defaults

CHANGELOG.md, go.mod, go.sum
We need to consume this patch to have the fix here https://github.com/giantswarm/clustertest/pull/117
It is necessary for upgrade tests. 
=> Bump clustertest to 0.12.1

CHANGELOG.md, internal/common/apps.go
Towards https://github.com/giantswarm/giantswarm/issues/28547
This PR adds a cross-provider test to check if all observability-bundle apps are deployed correctly.
=> add cross-provider observability-bundle test

CHANGELOG.md, internal/common/apps.go
This PR increases the timeout period for observability-bundle apps from 15 to 25min. As some tests run by the CI are failing whereas all those run manually succeeded, I guess this is mainly caused by the short timeout period which doesn't give enough time for the apps to deploy. 
If this doesn't work, I'll try to add more log outputs for the tests to have a description of the apps' events.
=> Fix observability-bundle failing tests

CHANGELOG.md, go.mod, go.sum
- Fixes https://github.com/giantswarm/giantswarm/issues/28901
=> Increase char count of clusters to 20 chars

providers/capa/standard/test_data/cluster_values.yaml, providers/capa/upgrade/test_data/cluster_values.yaml, providers/capz/standard/test_data/cluster_values.yaml, providers/capz/upgrade/test_data/cluster_values.yaml, providers/eks/standard/test_data/cluster_values.yaml, providers/eks/upgrade/test_data/cluster_values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/29041
=> Use max node pool name length

CHANGELOG.md, internal/upgrade/upgrade.go, providers/capa/upgrade/capa_test.go, providers/capv/upgrade/capv_test.go, providers/capvcd/upgrade/capvcd_test.go, providers/capz/upgrade/capz_test.go, providers/eks/upgrade/eks_test.go
This PR adds `TestConfig` for upgrade tests so that providers can customize timeouts. CAPVCD is much slower than others and it requires longer timeouts. 
=> Add test config for upgrades

CHANGELOG.md, providers/capvcd/standard/test_data/cluster_values.yaml, providers/capvcd/upgrade/test_data/cluster_values.yaml
We hit timeouts while waiting for nodes since CAPVCD is super slow in node provisioning. We think it is OK to have 1 CP in WC tests.
=> Reduce the number of CP nodes from 3 to 1 in CAPVCD tests

CHANGELOG.md, providers/capa/private/capa_suite_test.go
=> Fix typo in CAPA private suite name

CHANGELOG.md, internal/suite/setup.go, providers/capa/private/capa_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/29482
Introduces a retrying check for the MC api-server being available. This is to work around a limitation of our VPN setup where it can take a short while before the VPN tunnel is useable after it has been idle for a long period of time.
=> Added retrying healthcheck to MC at start of suite

CHANGELOG.md, providers/capvcd/standard/capvcd_test.go, providers/capvcd/upgrade/capvcd_test.go
Disable the CAPVCD tests while we recove broken MC
(Skipping tests as this is just disabling)
=> Disable the CAPVCD tests while we recove broken MC

CHANGELOG.md, internal/common/hello.go
Implements a custom dialer for the HTTP client to perform the DNS lookup in code rather than relying on the host system. This should (hopefully) mean that the initial Not Found results aren't cached as the DNS nameserver is actually checked each time for the result. This should hopefully cut down on the flakey-ness of the hello-world test that fails because the domain doesn't resolve quick enough.
Fixes: https://github.com/giantswarm/giantswarm/issues/29469
=> Use custom dialer for hello-world call

CHANGELOG.md, internal/common/scale.go, providers/capa/private/test_data/cluster_values.yaml, providers/capa/standard/test_data/cluster_values.yaml, providers/capa/upgrade/test_data/cluster_values.yaml
Increases the minimum number of worker nodes on CAPA to 2 to hopefully avoid issues with the `hello-world` test not having enough resources to deploy the pod and timing out waiting for the scale up.
As part of this I have also update the scale test to be dynamic based on the current number of worker nodes found in the cluster, rather than hard coded.
=> Increase min nodes for CAPA and make scale test dynamic to no of nodes

CHANGELOG.md, internal/common/hello.go, providers/capa/standard/test_data/default-apps_values.yaml, providers/capa/upgrade/test_data/default-apps_values.yaml, providers/eks/standard/test_data/default-apps_values.yaml, providers/eks/upgrade/test_data/default-apps_values.yaml
* Refactors the `hello-world` tests to change them to individual, ordered test cases to get a better understanding of where things go wrong.
* Introduced a test case to check that the ingress status is updated with the load balancer hostname.
* Increased the timeout from 10 min to 15 min for the ingress test.
* Set `triggerLoopOnEvent` to true for external-dns to speed up reconciliation of Ingress resources
=> Refactor hello-world test to split into individual, ordered cases

CHANGELOG.md, assets/storage/storage.go
Required on CAPA as we now install the security-bundle by default
=> Add securityContext to pvc pod

CHANGELOG.md, providers/capz/standard/capz_test.go, providers/capz/upgrade/capz_test.go
Towards https://github.com/giantswarm/wepa/issues/51
- Disables bastion support for CAPZ
=> Disable Bastion Support for CAPZ

CHANGELOG.md, providers/capvcd/standard/capvcd_test.go, providers/capvcd/upgrade/capvcd_test.go
towards https://github.com/giantswarm/giantswarm/issues/29581
re-enables CAPVCD tests.
=> Re-enable CAPVCD tests on gerbil

CHANGELOG.md, internal/suite/setup.go
Fixes https://github.com/giantswarm/giantswarm/issues/29845
It looks like during the refactor I missed off setting the versions to `latest` when called from an upgrade tests 🤦 
I'm going to skip the tests as they don't run against upgrades from this repo.
=> Fix upgrade tests not installing latest released first

CHANGELOG.md, internal/common/hello.go, internal/helper/fileexists.go, providers/capa/private/capa_test.go, providers/capa/private/test_data/default-apps_values.yaml, providers/capa/private/test_data/ingress-nginx_values.yaml
Towards: https://github.com/giantswarm/roadmap/issues/3099
The ingress test for private capa clusters didn't work.
I needed to fix a few things here and there in order to make it run.
This PR is part of those fixes.
=> Fix ingress test for private CAPA clusters

CHANGELOG.md, providers/capv/standard/test_data/cluster_values.yaml, providers/capv/upgrade/test_data/cluster_values.yaml
=> Rely on CAPV default values for k8s version

CHANGELOG.md, cmd/standup/main.go
* Ensures the provided app versions are passed to the cluster builder
* Created the `results.json` file as soon as possible so that if the cluster creation fails the `teardown` command still has a file to use to clean up the failed cluster.
Skipping tests as this CLI isn't tested. Manual testing has been done.
=> Create results.json early when running standup

CHANGELOG.md, providers/eks/standard/eks_test.go, providers/eks/upgrade/eks_test.go
Marks the EKS tests as skipped as they are currently broken in `grizzly` and unlikely to be fixed in the next week or so.
Skipping.
=> Disable EKS tests

CHANGELOG.md, internal/common/certmanager.go
Increases the timeout when waiting for cert-manager to 2 minutes
=> Increase cert-manager test timeout to 2 minutes

CHANGELOG.md, providers/eks/standard/eks_test.go, providers/eks/upgrade/eks_test.go
enable EKS test at they are now on 1.25
=> re-enable-eks-tests

CHANGELOG.md, internal/common/common.go, internal/common/metrics.go, providers/capa/private/capa_test.go, providers/capa/standard/capa_test.go, providers/capa/upgrade/capa_test.go, providers/capv/standard/capv_test.go, providers/capv/upgrade/capv_test.go, providers/capvcd/standard/capvcd_test.go, providers/capvcd/upgrade/capvcd_test.go, providers/capz/standard/capz_test.go, providers/capz/upgrade/capz_test.go, providers/eks/standard/eks_test.go, providers/eks/upgrade/eks_test.go
avoid checking presence of k8s control plane metrics in eks
=> Avoid checking control plane metrics in EKS.

CHANGELOG.md, cmd/standup/main.go
Increases the cluster creation timeout to try and avoid test flakes caused by slow infra.
=> Increase cluster creation timeout to 30 minutes

CHANGELOG.md, go.mod, go.sum, internal/suite/setup.go
Fixes https://github.com/giantswarm/giantswarm/issues/30298
Include the MCs API server endpoint in the log output to make it clear which cluster we are running the tests against.
=> Include the MC endpoint in log message to indeicate which MC

CHANGELOG.md, providers/capvcd/standard/test_data/cluster_values.yaml, providers/capvcd/upgrade/test_data/cluster_values.yaml
Switches the CAPVCD tests to use Flatcar as the base OS.
=> switch capvcd to flatcar

CHANGELOG.md, internal/common/metrics.go, internal/helper/prometheus.go
Towards:
https://github.com/giantswarm/giantswarm/issues/30424
adds support for mimir to the `metrics` test.
=> Add support for mimir in the `metrics` test.

CHANGELOG.md, providers/capvcd/standard/test_data/cluster_values.yaml, providers/capvcd/upgrade/test_data/cluster_values.yaml
towards https://github.com/giantswarm/giantswarm/issues/29353
- Increase CAPVCD CP node count to 3.
=> CAPVCD: re-enable HA CP with 3 nodes

CHANGELOG.md, providers/capvcd/standard/test_data/cluster_values.yaml, providers/capvcd/upgrade/test_data/cluster_values.yaml
In `cluster-cloud-director` `v0.50.0`, we move to a release model where K8s version and VM template are set in default values to be controlled by Giant Swarm through cluster app versions.
Towards https://github.com/giantswarm/roadmap/issues/3392
=> use default values of cluster-cloud-director chart:v0.50.0

CHANGELOG.md, go.mod, go.sum, internal/common/basic.go, internal/upgrade/upgrade.go
- Add common basic test that checks if Cluster Ready condition has Status=True.
- Add upgrade test that checks if control plane rolling update has finished (if it has started).
The second test here is the more important one, as it makes sure that a control plane rolling update has finished before it executes other tests.
Before having this control plane rolling update test, other post-upgrade tests would continue running even though the cluster upgrade has not been completed, so those test would make checks in a cluster that has a mix of old and new nodes.
Now with the new control plane rolling update test at least control plane nodes should be done with a rolling update, so the subsequent checks will be more reliable.
=> Check if Cluster is ready and if control plane rolling update has finished

CHANGELOG.md, README.md, go.mod, go.sum, internal/suite/setup.go, providers/capa/private/capa_suite_test.go, providers/capa/standard/capa_suite_test.go, providers/capa/upgrade/capa_suite_test.go, providers/capv/standard/capv_suite_test.go, providers/capv/upgrade/capv_suite_test.go, providers/capvcd/standard/capvcd_suite_test.go, providers/capvcd/upgrade/capvcd_suite_test.go, providers/capz/standard/capz_suite_test.go, providers/capz/upgrade/capz_suite_test.go, providers/eks/standard/eks_suite_test.go, providers/eks/upgrade/eks_suite_test.go
- Updated cluster-standup-teardown to v1.0.2
- Made use of new `clusterbuilder.KubeContext()` function
- Updated readme requirements
- Removed KubeContext const from each test suite
Blocked by https://github.com/giantswarm/cluster-test-suites/pull/276
=> Use KubeContext from cluster-standup-teardown

renovate.json5
Sets a specific Renovate config for the teleport dependencies to prevent the constant PRs every time the upstream repo has a new commit. Currently changed it to weekly but might eventually drop it to monthly if still too annoying.
@giantswarm/team-bigmac I've also added y'all as a reviewer specifically for this dependency so y'all are aware of the updates and can block any you know are going to cause problems.
FYI - I attempted to find a way to have the dependencies follow the releases on the GitHub repo but I couldn't find any way to manage that. I saw there was a [discussion upstream](https://github.com/renovatebot/renovate/discussions/27996) with someone asking the same with no replies. 😞
=> Add specific renovate config for teleport dep

CHANGELOG.md, go.mod, go.sum, internal/common/apps.go, internal/upgrade/upgrade.go
Towards https://github.com/giantswarm/roadmap/issues/3119
I ran tests locally (with this cluster-test-suites branch and [this cluster-aws PR](https://github.com/giantswarm/cluster-aws/pull/581)) and only this failed, but this same error happened also when I ran tests locally with cluster-test-suites main branch and latest release of with cluster-aws:
```
Common tests metrics [It] ensure key metrics are available on prometheus
/Users/nikola/src/giantswarm/cluster-test-suites/internal/common/metrics.go:88
[FAILED] Timed out after 600.002s.
Expected success, but got an error:
<*errors.errorString | 0x14000dab230>:
can't exec command in pod t-llcppvi2gcp16fa900-metrics-test: failed to exec command in pod - command terminated with exit code 1 (stderr: "Connecting to mimir-gateway.mimir:80 …
```
=> Add support for unified cluster-aws app

CHANGELOG.md, internal/upgrade/upgrade.go
This PR increases the node roll check timeout to 180 seconds instead of 25 seconds when doing the upgrade test. 
This is the time it waits for the control plane node roll status to update. 
=> Increase check time for upgrade status

CHANGELOG.md, internal/upgrade/upgrade.go
CAPVCD is slower than other providers and always times out when upgrading the CP nodes.
I tested manually and babysat a pipelinerun, it all works fine, it's just slow.
=> increase kubeadmcontrolplane rollout timeout from 20min to 30min

CHANGELOG.md, internal/upgrade/upgrade.go
Skip checking default-apps-aws version when unified cluster-aws app is deployed.
I missed this check in the original PR 🙈
=> Fix default-apps-aws check in upgrade test

README.md, providers/capa/cilium-eni-mode/capa_suite_test.go, providers/capa/cilium-eni-mode/capa_test.go, providers/capa/cilium-eni-mode/test_data/cluster_values.yaml, providers/capa/cilium-eni-mode/test_data/default-apps_values.yaml, providers/capa/cilium-eni-mode/test_data/helloworld_values.yaml, providers/capa/cilium-eni-mode/test_data/scale_helloworld_values.yaml
Towards https://github.com/giantswarm/roadmap/issues/2563
To ensure we're testing the right thing, I've added a basic "is this really ENI mode" check (pod IPs).
=> Add test for CAPA cluster in Cilium ENI mode

CHANGELOG.md, go.mod, go.sum, providers/capv/on-capz/test_data/cluster_values.yaml
Updates cluster-standup-teardown to v1.3.0
=> update cluster-standup-teardown to v1.3.0

CHANGELOG.md, go.mod, go.sum
Updates `cluster-standup-teardown` to v1.5.0 to pull in new cluster-cloud-director values.
=> Update cluster-standup-teardown to v1.5.0

README.md
Add the `--timeout` flag to the example commands as otherwise it is possible for the tests to fail if they take longer than 1 hour (e.g. the CAPA China test suite)
Skipping tests as just a readme update.
=> Add timeout flag to readme examples

CHANGELOG.md, go.mod, go.sum, internal/upgrade/upgrade.go
Switch to using new `ApplyBuiltCluster` in upgrade tests to avoid building the cluster twice.
=> Switch to using new `ApplyBuiltCluster` in upgrade tests

CHANGELOG.md, providers/capa/upgrade/test_data/cluster_values.yaml
- Increase node pool min size from 2 to 3 for CAPA upgrade test.
=> Increase node pool min size from 2 to 3 for CAPA upgrade test

CHANGELOG.md, internal/upgrade/upgrade.go
- Remove node checks from CAPA upgrade suite because we already check nodes in common tests after the upgrade.
=> Remove node checks from CAPA upgrade suite

CHANGELOG.md, providers/capa/upgrade/test_data/cluster_values.yaml
- Disable spot instances for CAPA upgrade suite, as we suspect that using spot instances is causing Upgrade suite failures lately.
=> Disable spot instances for CAPA upgrade suite

CHANGELOG.md, internal/suite/setup.go
Ensure that the timeout on the context passed in to the delete function in AfterSuite is always a value long enough to handle all cleanup needed.
=> Reset context timeout in AfterSuite

CHANGELOG.md, go.mod, go.sum, internal/common/apps.go, internal/common/basic.go, internal/common/common.go, internal/upgrade/upgrade.go
Alernative to https://github.com/giantswarm/cluster-test-suites/pull/339, just with less changes.
> [!NOTE]
> Currently before we upgrade the cluster, we just check if the nodes are ready. Just checking the nodes is IMO far from enough, and below additions are the bare minimum we should add now as these fix the issues that me and other folks have consistently noticed in different test runs (meaning more checks should be added in addition to these two below).
> [!WARNING]
> There is a change here in the PR to rename `runApps()` in `common` package to `RunApps()`, so we can reuse the app tests in upgrade tests as well (in addition to apps being tested in `common` tests). This is breaking the code structure as app tests (from `runApps()`) should be executed as a part of `common.Run(cfg)` …
=> Improve upgrade suites reliability

CHANGELOG.md, internal/common/scale.go
Towards: https://github.com/giantswarm/giantswarm/issues/31013 & https://github.com/giantswarm/roadmap/issues/3499
When the scale test is waiting for the expected number of replicas to be available we now log out the conditions of all the current pods as well as the taints of all the current worker nodes. This should allow us to better debug failures without needing to access the WC.
```
{"level":"info","ts":"2024-06-20T09:20:23+01:00","msg":"Checking for increased replicas. Expected: 3, Actual: 2"}
{"level":"info","ts":"2024-06-20T09:20:23+01:00","msg":"Condition messages from non-running deployment pods: [scale-hello-world-6d586889c8-g2mlq=0/6 nodes are available: 1 node(s) had untolerated taint {node.cluster.x-k8s.io/uninitialized: }, 2 node(s) didn't match pod anti-affinity rules, 3 …
```
=> Add extra logging to scale test

CHANGELOG.md, internal/common/certmanager.go
Towards: https://github.com/giantswarm/giantswarm/issues/31013
If the ClusterIssuer is not found we will attempt to get the status of the Helm `post-install` Job and any associated non-normal events to help debug failures without needing to re-run the suite.
=> Added more logging to ClusterIssuer test case

CHANGELOG.md, internal/common/hello.go
Towards: https://github.com/giantswarm/giantswarm/issues/31013
Adds a new test case to the hello-world tests to check that the associated Certificate is created and is ready.
Note: As we're now referencing types from cert-manager in multiple places it doesn't make sense to keep using the `unstructured` type. I won't do it as part of this PR but I plan to update `clustertest` to include the cert-manager schema in the kube client it creates that can then be used in these tests.
Example output:
```
Common tests hello world should have a ready Certificate generated
/Users/marcus/Code/GiantSwarm/cluster-test-suites/internal/common/hello.go:206
{"level":"info","ts":"2024-06-24T09:32:27+01:00","msg":"Checking for certificate 'hello-world-tls' in namespace 'giantswarm'"} …
```
=> Test for hello-world ingress Certificate ready

CHANGELOG.md, internal/common/basic.go, internal/upgrade/upgrade.go
Fixes: https://github.com/giantswarm/giantswarm/issues/31140
Adds a new basic check to ensure all Jobs in the WC have succeded.
=> Added test case to check all jobs succeded

CHANGELOG.md, go.mod, internal/common/certmanager.go, internal/common/hello.go
Fixes https://github.com/giantswarm/giantswarm/issues/31130
Switches to using the actual types from Cert-Manager when getting the `ClusterIssuer` and `Certificate` CRs.
=> Make use of cert-manager types

CHANGELOG.md, go.mod, go.sum, internal/common/apps.go, internal/common/certmanager.go
* Updated to latest `clustertest`
* Changed cert-manager tests to make use of Event helpers from `clustertest` (closes https://github.com/giantswarm/giantswarm/issues/31142)
* Trigger extra debugging to be logged when App-related tests fail with timeout. (Towards https://github.com/giantswarm/giantswarm/issues/31013)
=> Trigger extra debugging when app tests fail

CHANGELOG.md, go.mod, go.sum, internal/upgrade/upgrade.go
Towards: https://github.com/giantswarm/roadmap/issues/3537
Upgrades `clustertest` and `cluster-standup-teardown` with support for Release upgrades and modifies the upgrade test to ensure the cluster upgrade performs an upgrade to the release.
=> Support Release upgrades

CHANGELOG.md, internal/helper/upgrade.go, internal/suite/setup.go
Fix the upgrade suite skip check to allow running when testing against releases instead of just specific app versions.
Note: Skipping E2E tests as upgrade tests aren't able to be tested from this repo.
=> Fix upgrade tests for Releases test pipeline

internal/common/basic.go
=> Fixes unnecessary acronyms

CHANGELOG.md, go.mod, go.sum, internal/common/apps.go, internal/common/basic.go
Towards: https://github.com/giantswarm/giantswarm/issues/31013
Makes use of new failure handlers to add extra debug information when Deployments, DaemonSets or StatefulSets fail to become ready before the test timeout.
=> Added failure handling for not having expected number of ready replicas

CHANGELOG.md, go.mod, go.sum
bumps `cluster-standup-teardown` to the latest release
I'm skipping the e2e tests for now as this only affects CAPV. I'm testing those under [this pr](https://github.com/giantswarm/cluster-vsphere/pull/232)
=> updated cluster-standup-teardown to the latest release

CHANGELOG.md, internal/common/apps.go, internal/state/state.go, internal/timeout/consts.go, internal/timeout/doc.go, internal/timeout/type.go, providers/capa/china/capa_test.go
Fixes https://github.com/giantswarm/giantswarm/issues/31064
Introduces a way to set and get timeouts for specific test cases per test suite.
=> Added framework for overriding test timeouts

CHANGELOG.md, go.mod, go.sum
Update deps so CAPZ uses releases
=> Bump clustertest and cluster-standup-teardown

CHANGELOG.md, internal/upgrade/upgrade.go
Towards: https://github.com/giantswarm/roadmap/issues/3451
Skips the control plane rolling upgrade tests if the resource generation did not change (the control plane config didn't change and no rolling update is necessary).
Tested with local runs of the capa upgrade.
=> Skip rolling update control plane tests if the control plane resource did not change

CODEOWNERS
I noticed that the codeowners were incorrect after a refactor from quite a while ago 😅 
* Changed `common` to `internal` as it now is called
* Added EKS provider with Team Phoenix
* Added Team Bigmac of the owners of the teleport internal module
N/A
N/A
=> Update the codeowners for the repo

CHANGELOG.md, internal/suite/setup.go
Fixes https://github.com/giantswarm/roadmap/issues/3641
If the `BeforeSuite` fails we will attempt to grab the status of the cluster App to see if there has been any deployment errors.
Example:
```
{"level":"info","ts":"2024-08-22T13:55:13+01:00","msg":"Cluster App status: AppVersion='', Version='2.0.0-d7a8852053bca7655bf783c6e820cc85cdc4cc32', ReleaseStatus='deployed', ReleaseReason='', LastDeployed='2024-08-22 13:39:13 +0100 BST'"}
```
=> Log cluster App status on failure to standup cluster

CHANGELOG.md, README.md, providers/capa/cilium-eni-mode/test_data/cluster_values.yaml, providers/capa/private/test_data/cluster_values.yaml, providers/capa/standard/test_data/cluster_values.yaml, providers/capa/upgrade/test_data/cluster_values.yaml, providers/eks/standard/test_data/cluster_values.yaml, providers/eks/upgrade/test_data/cluster_values.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/29815
=> Set specific awsClusterRoleIdentityName for CAPA test suites

CHANGELOG.md, go.mod, go.sum, internal/common/basic.go, internal/upgrade/upgrade.go
Move some common functions to `clustertest` to make them reusable in other repos.
=> Move common functions to clustertest

CHANGELOG.md, internal/ecr/assets.go, internal/ecr/ecr.go, providers/capa/cilium-eni-mode/capa_test.go, providers/capa/private/capa_test.go, providers/capa/standard/capa_test.go, providers/capa/upgrade/capa_test.go
Adds a CAPA-specific test case to test pulling images from a private ECR repository. 
Example output:
```
Common tests ecr credential provider should be able to pull an image from a private ECR registry
/app/internal/ecr/ecr.go:46
{"level":"info","ts":"2024-10-07T14:58:23Z","msg":"Creating deployment with private ECR image..."}
{"level":"info","ts":"2024-10-07T14:58:23Z","msg":"Checking status of deployments replicas..."}
{"level":"info","ts":"2024-10-07T14:58:23Z","msg":"Deployment isn't yet ready - it currently has no replicas"}
{"level":"info","ts":"2024-10-07T14:58:33Z","msg":"Checking status of deployments replicas..."}
{"level":"info","ts":"2024-10-07T14:58:33Z","msg":"Deployment has 1 ready pod replicas"}
{"level":"info","ts":"2024-10-07T14:58:33Z","msg":"Deleting deployment..."}
• …
```
=> Added private ECR tests to CAPA test suites

CHANGELOG.md, go.mod, internal/suite/setup.go
Include some extra debugging of the WCs Cluster CR status when the cluster fails to standup.
Example output:
```
{"level":"info","ts":"2024-10-11T16:35:34+01:00","msg":"Attempting to get debug info for Cluster App"}
{"level":"info","ts":"2024-10-11T16:35:34+01:00","msg":"Cluster App status: AppVersion='', Version='0.61.0', ReleaseStatus='deployed', ReleaseReason='', LastDeployed='2024-10-11 16:16:02 +0100 BST'"}
{"level":"info","ts":"2024-10-11T16:35:34+01:00","msg":"Getting events for the Cluster App"}
{"level":"info","ts":"2024-10-11T16:35:34+01:00","msg":"No events found for Cluster App"}
{"level":"info","ts":"2024-10-11T16:35:34+01:00","msg":"Getting Cluster CR for the Cluster App"}
{"level":"info","ts":"2024-10-11T16:35:34+01:00","msg":"Cluster status: Phase='Provisioned', …
```
=> Add debugging of Cluster CR on standup failure

CHANGELOG.md, go.mod, go.sum
towards https://github.com/giantswarm/giantswarm/issues/31701
=> Updated clustertest and cluster-standup-teardown to support cluster-cloud-director as a unified app

CHANGELOG.md, go.mod, go.sum
- updates cluster-standup-teardown to 1.26.1
Test suites won't pass because this update is required to allow the vsphere test suite to pass.
=> Updated cluster-standup-teardown to 1.26.1

CHANGELOG.md, providers/eks/standard/eks_test.go, providers/eks/upgrade/eks_test.go
The EKS test sites have been flakey lately and a race condition is occasionally causing them to fail. As we currently aren't putting any effort into EKS I'm disabling these test suites for the time being until we decide to pick up the work on cluster-eks again.
Related: https://github.com/giantswarm/giantswarm/issues/31706 & https://github.com/giantswarm/roadmap/issues/3741
=> Skip EKS test suites

CHANGELOG.md, providers/capv/on-capa/capv_test.go, providers/capv/on-capz/capv_test.go
towards https://github.com/giantswarm/giantswarm/issues/32054
=> Skip capv-on-capa and capv-on-capz tests until we can figure out VPN routing to the new vSphere provider

CHANGELOG.md, go.mod, go.sum
towards https://github.com/giantswarm/giantswarm/issues/32054
=> Bump cluster-standup-teardown to v1.27.3 to update CAPV cluster values for the new vSphere provider

CHANGELOG.md, internal/timeout/consts.go, internal/upgrade/upgrade.go, providers/capvcd/upgrade/capvcd_test.go
Towards: https://github.com/giantswarm/releases/pull/1490
=> Allow to override `ClusterReady` timeout for cluster upgrade test

CHANGELOG.md, internal/common/basic.go, internal/timeout/consts.go, internal/upgrade/upgrade.go, providers/capvcd/upgrade/capvcd_test.go
=> Set CAPVCD `ClusterReady` timeout to 25Min in basic test

CHANGELOG.md, go.mod, go.sum
Use https://github.com/giantswarm/cluster-standup-teardown/pull/173 to prevent test from timing out because EC2 spot instances can't terminate quickly.
Chicken-egg problem, so I'll run these on the cluster-aws PR instead.
=> Bump `cluster-standup-teardown` to v1.27.4 to use lower lifecycle hooks heartbeat timeout to allow spot instances to terminate more quickly (CAPA)

CHANGELOG.md, internal/common/basic.go
Fixes: https://github.com/giantswarm/giantswarm/issues/32317
Adds a new common test to check for pods with containers that have restarted more than 3 times.
Example:
```
Common tests basic doesn't have restarting pods
/app/internal/common/basic.go:158
{"level":"info","ts":"2025-01-06T15:28:36Z","msg":"All (72) pods have containers with less restarts than the max allowed (3)"}
{"level":"info","ts":"2025-01-06T15:28:37Z","msg":"All (72) pods have containers with less restarts than the max allowed (3)"}
{"level":"info","ts":"2025-01-06T15:28:38Z","msg":"All (72) pods have containers with less restarts than the max allowed (3)"}
{"level":"info","ts":"2025-01-06T15:28:39Z","msg":"All (72) pods have containers with less restarts than the max allowed (3)"} …
```
=> Added test for CrashLooping pods

CHANGELOG.md, go.mod, go.sum
Bump `clustertest` to [v1.32.1](https://github.com/giantswarm/clustertest/releases/tag/v1.32.1) to fix timeout not being respected during `AfterSuite`. The timeout of 1 hour should now be respected and should cut down on leftover resources, especially from the CAPA China test suite.
=> Fix timeout not being respected during AfterSuite

CHANGELOG.md, internal/common/storage.go
- Refactored the storage test with the following changes:
- Split into individual it block for more fine-grained failures
- Added logging to show progress of tests while running
- Ensured the PersistentVolume is deleted before continuing to ensure we don't accidentally leave behind disks
Towards: https://github.com/giantswarm/roadmap/issues/3838
=> Refactor storage tests

CHANGELOG.md, internal/common/storage.go, internal/suite/setup.go
Fixed
- Ensure the storage test waits until PV has been fully deleted
Added
- Attempt to delete any remaining PVs during `AfterSuite` before the cluster itself is removed to try to avoid leaving cloud volumes behind.
Fixes: https://github.com/giantswarm/roadmap/issues/3838
=> Improved PV cleanup

CHANGELOG.md, go.mod, go.sum
Towards: https://github.com/giantswarm/giantswarm/issues/32434
=> Stop using spot instances for CAPA WCs

CHANGELOG.md, internal/ecr/ecr.go
See title. Without this, it's impossible to troubleshoot after the test ended.
/run cluster-test-suites TARGET_SUITES=./providers/capa/standard
=> Show debug info if `Deployment` with private ECR image failed

CHANGELOG.md, internal/common/basic.go
This PR increases the amount of flake attempts for the workload cluster connection check.
I've seen multiple runs where this test fails even though previous and following tests are all green.
=> Basic: Increase connection check flake attempts.

CHANGELOG.md, providers/capa/china/test_data/cluster_values.yaml, providers/capa/cilium-eni-mode/test_data/cluster_values.yaml, providers/capa/private/test_data/cluster_values.yaml, providers/capa/standard/test_data/cluster_values.yaml, providers/capa/upgrade/test_data/cluster_values.yaml
NTH may frequently restart during cluster creation due to IRSA operator being slow when creating the cluster openid provider in AWS. This makes the E2E tests fail regularly, although we consider it an expected situation. Until there's more granular control on the Pod restarting test conditions we'll disable NTH during E2E tests
=> Disable node-termination-handler in CAPA tests

CHANGELOG.md, internal/common/metrics.go
E2e tests currently failing for `v1.31` the metric name has to changed. It is backward compatible. The metric `apiserver_flowcontrol_request_concurrency_limit` does not exist in `v1.31`.
```
apiserver_flowcontrol_request_concurrency_limit
Nominal number of execution seats configured for each priority level
Stability Level:ALPHA
Type: Gauge
Labels:priority_level
Deprecated Versions:1.30.0
```
=> Change metric name from `apiserver_flowcontrol_request_concurrency_limit` to `apiserver_flowcontrol_nominal_limit_seats`

CHANGELOG.md, providers/capv/on-capa/test_data/cluster_values.yaml
towards https://github.com/giantswarm/giantswarm/issues/33674
we can't run the tests until the kubeconfig for the MC is updated in tekton.
=> Update capv-on-capa to use the new garm management cluster

CHANGELOG.md, internal/suite/setup.go
=> Fix `Setup` function to properly handle the case where the first release of a new major version is being tested.

CHANGELOG.md, internal/helper/report.go, internal/upgrade/upgrade.go
Towards: https://github.com/giantswarm/roadmap/issues/4003
Extending the upgrade test suite to automatically detect if nodes are rolled during a release upgrade.
A new test has been added to the upgrade suite that compares the set of cluster nodes before and after the upgrade is applied.
The result (true or false) is added to the Ginkgo test report under the `NODES_ROLLED` key.
This check can be disabled by setting the `SKIP_NODE_ROLL_DETECTION` environment variable, which is used to ignore expected node rolls (e.g., in "Previous Major" upgrade tests), because there we always roll the nodes.
A PR in `tekton-resources` will follow.
=> Add automatic node roll detection to upgrade tests
